config/routes.rb
Rails.application.routes.draw do
 


  get 'reservations/index'
  get 'resarvations/index'
  get 'rooms/index'
  root to: "home#index"
  devise_for :users, controllers: {
    registrations:  'users/registrations',
    sessions:       'users/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update'
  end

 get "/users/show" => "users#show"
 get "/users/profile" => "users#profile"
 get "/users/profile/edit" => "users#profile_edit"
 
  resources :rooms do
    collection do
      get "search"
      get "room/area/search"
    end
  end

  resources :reservations 

  get "/confirm/reservation" => "reservations#confirm"
  

  get "/search" => "rooms#room_search_result"
  get "/area/search" => "rooms#area_search_result"


end

app/models/room.rb
class Room < ApplicationRecord
    validates :name, presence: true
    validates :room_introduction, presence: true
    validates :price, presence: true, numericality: {greater_than_or_equal_to: 1}
    validates :address, presence: true

    belongs_to :user
    has_many :reservations

    mount_uploader :room_img, RoomImgUploader

    def self.all_search(search)
        if search
        Room.where("name LIKE ? or (room_introduction LIKE ?)", "%#{search}%","%#{search}%")
        else
        Room.all
        end
    end
    def self.area_search(search)
        if search
        Room.where("address LIKE ? ", "%#{search}%")
        else
        Room.all
        end
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @user = current_user
    @rooms = Room.where(user_id: @user.id)
  end

  def show
   
    @room = Room.find(params[:id])
    @user = current_user
   
    @reservation = Reservation.new
    
    
    
    
  end

  def new
    @user = current_user
    @room = Room.new
  end

  def edit
    @room = Room.find_by(id: params[:id])
  end

  def create
    @room = Room.new(params.require(:room).permit(:name, :room_introduction, :price, :address, :user_id, :room_img))
    if @room.save
      flash[:notice]= "新規登録しました"  
      redirect_to "/"
    end
  end

  def update
    @room = Room.find_by(id: params[:id])
    if @room.update(params.require(:room).permit(:name, :room_introduction, :price, :address, :user_id, :room_img))
       redirect_to room_path
    end
  end
  def room_search_result
    @rooms = Room.all_search(params[:search])
    @cnt = Room.all_search(params[:search]).count
    
  end
  def area_search_result
    @rooms = Room.area_search(params[:search])
    @cnt = Room.area_search(params[:search]).count
    render "/rooms/room_search_result"
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<h1>施設情報の編集</h1>

<%= form_with model: @room, url: room_path, method: :patch do |f| %>
    <table>
    <tr>
        <th><%= f.label :name, "施設名" %></th>
        <td><%= f.text_field :name %></td>
    </tr>
    <tr>
        <th><%= f.label :room_introduction, "施設紹介" %></th>
        <td><%= f.text_area :room_introduction %></td>
    </tr>
    <tr>
        <th><%= f.label :price, "料金" %></th>
        <td><%= f.text_field :price %></td>
    </tr>
    <tr>
        <th><%= f.label :address, "住所" %></th>
        <td><%= f.text_field :address %></td>
    </tr>
    <tr>
        <th><%= f.label :room_img, "施設画像" %></th>
        <td><%= f.file_field :room_img %></td>
    </tr>
    </table>
  
    <div>
    <%= f.submit "編集を完了する" %>
    <%= link_to "登録施設一覧に戻る", rooms_index_path %>
<% end %>

app/views/rooms/index.html.erb
<h1>登録済み一覧</h1>
<table>
<tr>
<th>施設画像</th><th>施設名</th><th>施設紹介</th><th>料金</th><th>作成日</th>
</tr>
<% @rooms.each do |room| %>
<tr>
<td><%= image_tag room.room_img.url%></td><td><%= room.name %></td><td><%= room.room_introduction %></td><td><%= room.price %></td><td><%= room.created_at.strftime('%Y/%m/%d')  %></td><td><%= link_to "編集" , "/rooms/#{room.id}/edit" %></td>
</tr>
</table>
<% end %>

app/views/rooms/new.html.erb
<h1>新規登録</h1>

<%= form_with model: @room, url: rooms_path do |f| %>
    <table>
    <tr>
        <th><%= f.label :name, "施設名" %></th>
        <td><%= f.text_field :name %></td>
    </tr>
    <tr>
        <th><%= f.label :room_introduction, "施設紹介" %></th>
        <td><%= f.text_area :room_introduction %></td>
    </tr>
    <tr>
        <th><%= f.label :price, "料金" %></th>
        <td><%= f.text_field :price %></td>
    </tr>
    <tr>
        <th><%= f.label :address, "住所" %></th>
        <td><%= f.text_field :address %></td>
    </tr>
    <tr>
        <th><%= f.label :room_img, "施設画像" %></th>
        <td><%= f.file_field :room_img %></td>
    </tr>
    </table>
    <%= f.hidden_field :user_id, value: @user.id %>
    <div>
    <%= f.submit "登録を完了する" %>
    <% end %>

app/views/rooms/room_search_result.html.erb
<h2><%= "#{@cnt}件が見つかりました" %></h2>
<div>
<%= form_tag(area_search_path, method: :get) do %>
    <%= text_field_tag :search, placeholder="エリア名を入力" %>
    <%= submit_tag "検索", :name => nil %>
    <% end %>

    <%= form_tag(search_path, method: :get) do %>
        <%= text_field_tag :search, placeholder="キーワード名を入力" %>
        <%= submit_tag "検索", :name => nil %>
        <% end %>
</div>

<table>
<tr>
<th>施設名</th><th>住所</th><th>施設紹介</th><th>料金</th>
</tr>
<% @rooms.each do |room| %>
<tr>
<td><%= room.name %></td><td><%= room.address %></td><td><%= room.room_introduction %></td><td><%= room.price %></td><td><%= link_to "詳細はこちら" , "/rooms/#{room.id}" %></td>
</tr>

<% end %>
</table>

app/views/rooms/show.html.erb
<% if @reservation.errors.any? %>
  <div class = "alert">
    <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div>
<%= link_to "←戻る", :back %>
<%= link_to "編集", "/rooms/#{@room.id}/edit" %>
</div>

<%= image_tag @room.room_img.url %>

<div>
<h2><%= @room.name %></h2>
<h3><%= @room.price %></h3>
<p><%= @room.address %></p>
<p><%= @room.room_introduction %></p>

</div>


<%= form_with  model: @reservation,  url: confirm_reservation_path,  method: :get do |f| %>
  
<table>
<tr>
<th>チェックイン</th>
<td><%= f.date_field :check_in_date %></td>
</tr>
<tr>
<th>チェックアウト</th>
<td><%= f.date_field :check_out_date %></td>
</tr>
<tr>
<th>人数</th>
<td><%= f.number_field :people_number, min: 1 %></td>
</tr>
</table>
<%= f.hidden_field :room_id, value: @room.id %>
<%= f.submit "予約する" %>

<% end %>