config/routes.rb
Rails.application.routes.draw do
 


  get 'reservations/index'
  get 'resarvations/index'
  get 'rooms/index'
  root to: "home#index"
  devise_for :users, controllers: {
    registrations:  'users/registrations',
    sessions:       'users/sessions'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update'
  end

 get "/users/show" => "users#show"
 get "/users/profile" => "users#profile"
 get "/users/profile/edit" => "users#profile_edit"
 
  resources :rooms do
    collection do
      get "search"
      get "room/area/search"
    end
  end

  resources :reservations 

  get "/confirm/reservation" => "reservations#confirm"
  

  get "/search" => "rooms#room_search_result"
  get "/area/search" => "rooms#area_search_result"


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StayReservationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
    <meta name="turbolinks-visit-control" content="reload">
  </head>

  <body>
  <header>
  <div class="header_container">
    <div class="header_items">
      <p class="header_title"><%= link_to "Potepan Share", "/" %></p>
    </div>
    <% if user_signed_in? %>
    <div class="header_buttons">
      <%= image_tag current_user.user_img.url class: "header_buttons" %>
      <button class="dropdown_btn" id="dropdown_btn"><%= "#{current_user.name}"%></button>
      <div class="dropdown_body" >
        <ul class="dropdwon_list">
          <li class="dropdown_item"><%= link_to "施設の新規登録", new_room_path%></li>
          <li class="dropdown_item"><%= link_to "予約済み一覧", reservations_path %></li>
          <li class="dropdown_item"><%= link_to "登録済み一覧", rooms_index_path %></li>
          <li class="dropdown_item"> <%= link_to "アカウント設定", users_show_path %></li>
          <li class="dropdown_item"><%= button_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div> 
    <% else %>
    <div class= "header_buttons">
      <button class="header_button"><%= link_to "ログイン",new_user_session_path %></button>
      <button class="header_button"><%= link_to "新規登録",new_user_registration_path %></button>
    </div>
  </div>
  <% end %>

  </header>

  
    <%= yield %>

  <footer>
  <div class="footer_container">
    <div class="footer_items">
      <p class="footer_title">Potepan Share</p>
      <p class="footer_subtitle">Copyright © Potepan Share2024 All rights reserved</p>
    </div>
  </div>
  </footer>
  <script type="text/javascript" src="/dropdown.js"></script>

  </body>
</html>